//Rock, paper, scissors JavaScript simulator.

//This is the user input
const getUserChoice = userInput => {
  userInput = userInput.toLowerCase();
if (userInput === 'rock' || userInput === 'paper' || userInput === 'scissors')  {
  return userInput;
} else {
  console.log('Error!');
}
};

//This is the random input generated by the computer.
function getComputerChoice()  {
  getComputerChoice = Math.floor(Math.random() * 3);
  switch(getComputerChoice)  {
    case 0:
      return 'rock';
    case 1:
      return 'paper';
    case 2:
      return 'scissors';
  }
};

//This dictates who wins the round.
function determineWinner(userChoice, computerChoice)  {
  if (userChoice === computerChoice)  {
    return 'It\'s a tie!';
  }
  else if (userChoice === 'rock' && computerChoice === 'scissors')  {
    return 'Player wins!';
  }
  else if (userChoice === 'paper' && computerChoice === 'rock')  {
    return 'Player wins!';
  }
  else if (userChoice === 'scissors' && computerChoice === 'paper')  {
    return 'Player wins!';
  } else {
    return 'Computer wins!';
  }
}

  //This creates the message of what happened during the game.
const playGame = () => {
  //'scissors' below is just a placeholder, change to whatever the user input is.
  const userChoice = getUserChoice('scissors');
  const computerChoice = getComputerChoice();
  console.log('You chose: ' + userChoice);
  console.log('The computer chose: ' + computerChoice);
  console.log('The result: ' + determineWinner(userChoice, computerChoice));
};

playGame();







